export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";
export const FETCH_PRODUCTS_BY_BRAND = "FETCH_PRODUCTS_BY_BRAND";
export const FETCH_PRODUCTS_BY_GENDER = "FETCH_PRODUCTS_BY_GENDER";
export const FETCH_PRODUCTS_BY_NAME= "FETCH_PRODUCTS_BY_NAME";
export const FETCH_PRODUCTS_BY_CATEGORY= "FETCH_PRODUCTS_BY_CATEGORY";
export const FETCH_PRODUCTS_BY_PRICE= "FETCH_PRODUCTS_BY_PRICE";

export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const LOADING_CART = "LOADING_CART";
export const PRODUCT_ADDED_TO_CART_SUCCESS = "PRODUCT_ADDED_TO_CART_SUCCESS";
export const PRODUCT_REMOVED_FROM_CART_SUCCESS = "PRODUCT_REMOVED_FROM_CART_SUCCESS";

export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ALL_USERS_ORDERS_SUCCESS = "FETCH_ALL_USERS_ORDERS_SUCCESS";
export const FETCH_USER_ORDERS_SUCCESS = "FETCH_ALL_ORDERS_SUCCESS";
export const ORDER_ADDED_SUCCESS = "ORDER_ADDED_SUCCESS";
export const ORDER_ADDED_FAILURE = "ORDER_ADDED_FAILURE";
export const ORDER_CONFIRMED_SUCCESS = "ORDER_CONFIRMED_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILURE = "PASSWORD_RESET_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const RESET_PASSWORD_CODE_SUCCESS = "RESET_PASSWORD_CODE_SUCCESS";
export const RESET_PASSWORD_CODE_FAILURE = "RESET_PASSWORD_CODE_FAILURE";
export const FORM_RESET = "FORM_RESET";

export const PRODUCT_ADDED_SUCCESS = "PRODUCT_ADDED_SUCCESS";
export const PRODUCT_UPDATED_SUCCESS = "PRODUCT_UPDATED_SUCCESS";
export const PRODUCT_ADDED_FAILURE = "PRODUCT_ADDED_FAILURE";
export const PRODUCT_UPDATED_FAILURE = "PRODUCT_UPDATED_FAILURE";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";

export const USER_UPDATED_SUCCESS = "USER_UPDATED_SUCCESS";
export const USER_ADDED_RATING_SUCCESS = "USER_ADDED_RATING_SUCCESS";
export const USER_ADDED_RATING_FAILURE = "USER_ADDED_RATING_FAILURE";

