#FROM openjdk:11-jre-slim
#LABEL authors="vietho"
#WORKDIR /myapp
#COPY target/Assignment-EcommerceProject-BackEnd-0.0.1-SNAPSHOT.war /myapp/myapp.war
#ENV SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-host:5432/perfumeStore
#ENV SPRING_DATASOURCE_USERNAME=postgres
#ENV SPRING_DATASOURCE_PASSWORD=020501
#EXPOSE 8080
#
#ENTRYPOINT ["java", "-jar", "myapp.war"]